
import { Kysely, sql } from 'kysely'

export async function up(db: Kysely<any>): Promise<void> {
  // Create duty_assignments table
  await db.schema
    .createTable('duty_assignments')
    .addColumn('id', 'serial', (col) => col.primaryKey())
    .addColumn('officer_id', 'integer', (col) => col.notNull())
    .addColumn('assignment_type', 'varchar', (col) => col.check(sql`assignment_type IN ('Primary', 'Backup', 'Emergency')`).notNull())
    .addColumn('start_date', 'timestamp', (col) => col.notNull())
    .addColumn('end_date', 'timestamp', (col) => col.notNull())
    .addColumn('shift_pattern', 'varchar', (col) => col.check(sql`shift_pattern IN ('24_48', 'M_F')`).notNull())
    .addColumn('is_active', 'boolean', (col) => col.defaultTo(true).notNull())
    .addColumn('station_coverage', 'jsonb')
    .addColumn('created_at', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addForeignKeyConstraint('duty_assignments_officer_id_fk', ['officer_id'], 'users', ['id'])
    .execute()

  // Create contact_attempts table
  await db.schema
    .createTable('contact_attempts')
    .addColumn('id', 'serial', (col) => col.primaryKey())
    .addColumn('absence_id', 'integer', (col) => col.notNull())
    .addColumn('manager_id', 'integer', (col) => col.notNull())
    .addColumn('attempt_date', 'timestamp', (col) => col.notNull())
    .addColumn('contact_method', 'varchar', (col) => col.check(sql`contact_method IN ('Phone', 'Email', 'In Person', 'SMS', 'App')`).notNull())
    .addColumn('successful', 'boolean', (col) => col.defaultTo(false).notNull())
    .addColumn('notes', 'text')
    .addColumn('next_scheduled_contact', 'timestamp')
    .addColumn('follow_up_required', 'boolean', (col) => col.defaultTo(false).notNull())
    .addColumn('created_at', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addForeignKeyConstraint('contact_attempts_absence_id_fk', ['absence_id'], 'absences', ['id'])
    .addForeignKeyConstraint('contact_attempts_manager_id_fk', ['manager_id'], 'users', ['id'])
    .execute()

  // Create required_documents table
  await db.schema
    .createTable('required_documents')
    .addColumn('id', 'serial', (col) => col.primaryKey())
    .addColumn('absence_id', 'integer', (col) => col.notNull())
    .addColumn('document_type', 'varchar', (col) => col.check(sql`document_type IN ('Doctor Note', 'WorkSafe Form', 'Return-to-Work', 'Medical Certificate', 'Incident Report')`).notNull())
    .addColumn('due_date', 'timestamp', (col) => col.notNull())
    .addColumn('submitted_date', 'timestamp')
    .addColumn('status', 'varchar', (col) => col.check(sql`status IN ('Required', 'Submitted', 'Reviewed', 'Rejected')`).notNull())
    .addColumn('file_path', 'varchar')
    .addColumn('reviewed_by_id', 'integer')
    .addColumn('created_at', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addColumn('updated_at', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addForeignKeyConstraint('required_documents_absence_id_fk', ['absence_id'], 'absences', ['id'])
    .addForeignKeyConstraint('required_documents_reviewed_by_fk', ['reviewed_by_id'], 'users', ['id'])
    .execute()

  // Create communication_log table
  await db.schema
    .createTable('communication_log')
    .addColumn('id', 'serial', (col) => col.primaryKey())
    .addColumn('absence_id', 'integer', (col) => col.notNull())
    .addColumn('communication_type', 'varchar', (col) => col.check(sql`communication_type IN ('Phone', 'Email', 'SMS', 'In-Person', 'App')`).notNull())
    .addColumn('direction', 'varchar', (col) => col.check(sql`direction IN ('Outbound', 'Inbound')`).notNull())
    .addColumn('participant_ids', 'jsonb')
    .addColumn('summary', 'text', (col) => col.notNull())
    .addColumn('key_points', 'jsonb')
    .addColumn('action_items', 'jsonb')
    .addColumn('follow_up_required', 'boolean', (col) => col.defaultTo(false).notNull())
    .addColumn('sentiment_score', 'integer')
    .addColumn('communication_date', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addForeignKeyConstraint('communication_log_absence_id_fk', ['absence_id'], 'absences', ['id'])
    .execute()

  // Create self-reporting tables
  await db.schema
    .createTable('self_reporting_eligibility')
    .addColumn('id', 'serial', (col) => col.primaryKey())
    .addColumn('employee_id', 'integer', (col) => col.notNull())
    .addColumn('is_eligible', 'boolean', (col) => col.defaultTo(false).notNull())
    .addColumn('eligibility_reason', 'varchar')
    .addColumn('max_self_report_days', 'integer', (col) => col.defaultTo(3).notNull())
    .addColumn('allowed_absence_types', 'jsonb')
    .addColumn('requires_manager_approval', 'boolean', (col) => col.defaultTo(true).notNull())
    .addColumn('auto_approval_threshold', 'integer', (col) => col.defaultTo(2).notNull())
    .addColumn('eligibility_start_date', 'timestamp', (col) => col.notNull())
    .addColumn('eligibility_end_date', 'timestamp')
    .addColumn('review_frequency_days', 'integer', (col) => col.defaultTo(90).notNull())
    .addColumn('last_review_date', 'timestamp')
    .addColumn('created_at', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addColumn('updated_at', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addForeignKeyConstraint('self_reporting_eligibility_employee_fk', ['employee_id'], 'users', ['id'])
    .execute()

  await db.schema
    .createTable('self_reporting_logs')
    .addColumn('id', 'serial', (col) => col.primaryKey())
    .addColumn('employee_id', 'integer', (col) => col.notNull())
    .addColumn('report_date', 'timestamp', (col) => col.notNull())
    .addColumn('absence_type', 'varchar', (col) => col.notNull())
    .addColumn('duration_days', 'integer', (col) => col.notNull())
    .addColumn('auto_approved', 'boolean', (col) => col.defaultTo(false).notNull())
    .addColumn('manager_review_required', 'boolean', (col) => col.defaultTo(false).notNull())
    .addColumn('manager_reviewed_by', 'integer')
    .addColumn('review_date', 'timestamp')
    .addColumn('review_notes', 'text')
    .addColumn('compliance_score', 'integer')
    .addColumn('created_at', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addForeignKeyConstraint('self_reporting_logs_employee_fk', ['employee_id'], 'users', ['id'])
    .addForeignKeyConstraint('self_reporting_logs_reviewed_by_fk', ['manager_reviewed_by'], 'users', ['id'])
    .execute()

  // Create wellness tables
  await db.schema
    .createTable('wellness_indicators')
    .addColumn('id', 'serial', (col) => col.primaryKey())
    .addColumn('employee_id', 'integer', (col) => col.notNull())
    .addColumn('indicator_type', 'varchar', (col) => col.check(sql`indicator_type IN ('Fatigue', 'Stress', 'Burnout', 'Physical Strain')`).notNull())
    .addColumn('indicator_level', 'varchar', (col) => col.check(sql`indicator_level IN ('Low', 'Medium', 'High', 'Critical')`).notNull())
    .addColumn('source', 'varchar', (col) => col.check(sql`source IN ('Self-Report', 'Manager Observation', 'System Detection')`).notNull())
    .addColumn('recorded_date', 'timestamp', (col) => col.notNull())
    .addColumn('intervention_recommended', 'boolean', (col) => col.defaultTo(false).notNull())
    .addColumn('intervention_applied', 'boolean', (col) => col.defaultTo(false).notNull())
    .addColumn('follow_up_date', 'timestamp')
    .addColumn('created_at', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addForeignKeyConstraint('wellness_indicators_employee_fk', ['employee_id'], 'users', ['id'])
    .execute()

  await db.schema
    .createTable('preventive_interventions')
    .addColumn('id', 'serial', (col) => col.primaryKey())
    .addColumn('employee_id', 'integer', (col) => col.notNull())
    .addColumn('intervention_type', 'varchar', (col) => col.check(sql`intervention_type IN ('Peer Support', 'EAP Referral', 'Light Duty', 'Time Off', 'Wellness Program')`).notNull())
    .addColumn('recommended_by', 'integer', (col) => col.notNull())
    .addColumn('implementation_date', 'timestamp', (col) => col.notNull())
    .addColumn('effectiveness_rating', 'integer')
    .addColumn('notes', 'text')
    .addColumn('follow_up_required', 'boolean', (col) => col.defaultTo(false).notNull())
    .addColumn('created_at', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addForeignKeyConstraint('preventive_interventions_employee_fk', ['employee_id'], 'users', ['id'])
    .addForeignKeyConstraint('preventive_interventions_recommended_by_fk', ['recommended_by'], 'users', ['id'])
    .execute()

  // Create return-to-work tables
  await db.schema
    .createTable('return_to_work_plans')
    .addColumn('id', 'serial', (col) => col.primaryKey())
    .addColumn('absence_id', 'integer', (col) => col.notNull())
    .addColumn('plan_type', 'varchar', (col) => col.check(sql`plan_type IN ('Standard', 'Graduated', 'Accommodated')`).notNull())
    .addColumn('start_date', 'timestamp', (col) => col.notNull())
    .addColumn('expected_full_duty_date', 'timestamp', (col) => col.notNull())
    .addColumn('current_phase', 'integer', (col) => col.defaultTo(1).notNull())
    .addColumn('phase_details', 'jsonb')
    .addColumn('medical_restrictions', 'jsonb')
    .addColumn('accommodations_required', 'jsonb')
    .addColumn('supervisor_approval_required', 'boolean', (col) => col.defaultTo(false).notNull())
    .addColumn('hr_approval_required', 'boolean', (col) => col.defaultTo(false).notNull())
    .addColumn('plan_status', 'varchar', (col) => col.check(sql`plan_status IN ('Active', 'Completed', 'Modified')`).notNull())
    .addColumn('created_at', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addColumn('updated_at', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addForeignKeyConstraint('return_to_work_plans_absence_id_fk', ['absence_id'], 'absences', ['id'])
    .execute()

  await db.schema
    .createTable('rtw_phase_progress')
    .addColumn('id', 'serial', (col) => col.primaryKey())
    .addColumn('plan_id', 'integer', (col) => col.notNull())
    .addColumn('phase_number', 'integer', (col) => col.notNull())
    .addColumn('start_date', 'timestamp', (col) => col.notNull())
    .addColumn('end_date', 'timestamp')
    .addColumn('duties_assigned', 'jsonb')
    .addColumn('hours_per_shift', 'integer', (col) => col.notNull())
    .addColumn('restrictions_in_place', 'jsonb')
    .addColumn('phase_completed', 'boolean', (col) => col.defaultTo(false).notNull())
    .addColumn('employee_feedback', 'integer')
    .addColumn('supervisor_assessment', 'integer')
    .addColumn('created_at', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addColumn('updated_at', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addForeignKeyConstraint('rtw_phase_progress_plan_id_fk', ['plan_id'], 'return_to_work_plans', ['id'])
    .execute()

  // Create analytics tables
  await db.schema
    .createTable('cost_calculations')
    .addColumn('id', 'serial', (col) => col.primaryKey())
    .addColumn('absence_id', 'integer', (col) => col.notNull())
    .addColumn('salary_cost', 'decimal', (col) => col.notNull())
    .addColumn('overtime_cost', 'decimal', (col) => col.notNull())
    .addColumn('replacement_cost', 'decimal', (col) => col.notNull())
    .addColumn('administrative_cost', 'decimal', (col) => col.notNull())
    .addColumn('total_cost', 'decimal', (col) => col.notNull())
    .addColumn('cost_category', 'varchar', (col) => col.check(sql`cost_category IN ('Direct', 'Indirect', 'Opportunity')`).notNull())
    .addColumn('calculated_date', 'timestamp', (col) => col.notNull())
    .addColumn('notes', 'text')
    .addColumn('created_at', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addForeignKeyConstraint('cost_calculations_absence_id_fk', ['absence_id'], 'absences', ['id'])
    .execute()

  await db.schema
    .createTable('resource_impact')
    .addColumn('id', 'serial', (col) => col.primaryKey())
    .addColumn('absence_id', 'integer', (col) => col.notNull())
    .addColumn('station_id', 'integer', (col) => col.notNull())
    .addColumn('shift_date', 'timestamp', (col) => col.notNull())
    .addColumn('minimum_staffing_met', 'boolean', (col) => col.defaultTo(true).notNull())
    .addColumn('backup_required', 'boolean', (col) => col.defaultTo(false).notNull())
    .addColumn('overtime_required', 'boolean', (col) => col.defaultTo(false).notNull())
    .addColumn('service_level_impact', 'varchar', (col) => col.check(sql`service_level_impact IN ('None', 'Minor', 'Moderate', 'Major')`).notNull())
    .addColumn('response_time_impact', 'integer')
    .addColumn('notes', 'text')
    .addColumn('created_at', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addForeignKeyConstraint('resource_impact_absence_id_fk', ['absence_id'], 'absences', ['id'])
    .addForeignKeyConstraint('resource_impact_station_id_fk', ['station_id'], 'stations', ['id'])
    .execute()

  await db.schema
    .createTable('employee_feedback')
    .addColumn('id', 'serial', (col) => col.primaryKey())
    .addColumn('absence_id', 'integer', (col) => col.notNull())
    .addColumn('feedback_type', 'varchar', (col) => col.check(sql`feedback_type IN ('Process', 'Support', 'Communication', 'Overall')`).notNull())
    .addColumn('rating', 'integer', (col) => col.notNull())
    .addColumn('comments', 'text')
    .addColumn('submitted_anonymously', 'boolean', (col) => col.defaultTo(false).notNull())
    .addColumn('improvement_suggestions', 'text')
    .addColumn('follow_up_required', 'boolean', (col) => col.defaultTo(false).notNull())
    .addColumn('action_taken', 'jsonb')
    .addColumn('feedback_date', 'timestamp', (col) => col.defaultTo(sql`now()`).notNull())
    .addForeignKeyConstraint('employee_feedback_absence_id_fk', ['absence_id'], 'absences', ['id'])
    .execute()

  // Create additional indexes
  await db.schema
    .createIndex('contact_attempts_absence_id_index')
    .on('contact_attempts')
    .column('absence_id')
    .execute()

  await db.schema
    .createIndex('self_reporting_eligibility_employee_index')
    .on('self_reporting_eligibility')
    .column('employee_id')
    .execute()

  await db.schema
    .createIndex('return_to_work_plans_absence_id_index')
    .on('return_to_work_plans')
    .column('absence_id')
    .execute()

  await db.schema
    .createIndex('cost_calculations_absence_id_index')
    .on('cost_calculations')
    .column('absence_id')
    .execute()
}

export async function down(db: Kysely<any>): Promise<void> {
  // Drop tables in reverse order
  await db.schema.dropTable('employee_feedback').execute()
  await db.schema.dropTable('resource_impact').execute()
  await db.schema.dropTable('cost_calculations').execute()
  await db.schema.dropTable('rtw_phase_progress').execute()
  await db.schema.dropTable('return_to_work_plans').execute()
  await db.schema.dropTable('preventive_interventions').execute()
  await db.schema.dropTable('wellness_indicators').execute()
  await db.schema.dropTable('self_reporting_logs').execute()
  await db.schema.dropTable('self_reporting_eligibility').execute()
  await db.schema.dropTable('communication_log').execute()
  await db.schema.dropTable('required_documents').execute()
  await db.schema.dropTable('contact_attempts').execute()
  await db.schema.dropTable('duty_assignments').execute()
}